x = (input("Give me the first number : "))
y = (input("Give me the second number : "))
x = float(x)
y = float(y)
print("Thank you!")
print(f"{x} + {y} = {x + y}")
print(f"{x} - {y} = {x - y}")
print(f"{x} / {y} = {x / y}")
print(f"{x} * {y} = {x * y}")

